version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-eks: circleci/aws-eks@0.2

jobs:
  install-helm-chart:
    docker:
      image: yjkim1ntels/helm3-kubectl-docker
    steps:
      - checkout
      - run: 
          name: Install AWS cli
            command: |
              sudo apt-get update
              sudo apt-get install -y awscli
      - run:
          name: Get the kubeconfig file
            comnand: |
              helm version
              aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME
              cat ~/.kube/config
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: helloapp
          tag: "$CIRCLE_SHA1"
      - install-helm-chart:
          cluster-name: terraform-eks-demo
          requires:
            - aws-ecr/build-and-push-image