version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: 
        name: Install AWS cli
        command: | 
          sudo apt-get update -y
          sudo apt-get install -y awscli
        
#workflows:
#  build_and_push_image:
#    jobs:
      #- aws-ecr/build-and-push-image:
      #    account-url: AWS_ECR_URL
      #    aws-access-key-id: AWS_ACCESS_KEY_ID
      #    aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      #    create-repo: true
      #    dockerfile: Dockerfile
      #    path: .
      #    region: AWS_REGION
      #    repo: helloapp
      #    tag: "$CIRCLE_SHA1"
#      - build:
      #    requires:
      #      - aws-ecr/build-and-push-image