version: 2.1

jobs:
  builb:
    docker: 
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: | 
            apk add --no-cache curl jq py-pip
            pip install awscli 
      - run:
          name: Build Image
          command: | 
            $(aws ecr get-login --no-include-email --region us-east-1)
            systemctl start docker
            docker build -t 686978187267.dkr.ecr.ap-southeast-1.amazonaws.com/helloapp:$CIRCLE_SHA1 .
      - run:
          name: Push Image
          command: | 
            docker push 686978187267.dkr.ecr.ap-southeast-1.amazonaws.com/helloapp:$CIRCLE_SHA1      
  deploy: 
    docker:
      - image: dtzar/helm-kubectl
    steps:
      - checkout
      - run: 
          name: Install AWS cli
          command: | 
            apk add --no-cache curl jq py-pip
            pip install awscli
      - run:
          name: Get the kubeconfig file
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME
            cat ~/.kube/config
      - run:
          name: Helm Upgrade Or Install
          command: |
            helm upgrade helloapp ~/project/chart/hello/ --namespace default --set image.repository=686978187267.dkr.ecr.ap-southeast-1.amazonaws.com/helloapp --set image.tag=$CIRCLE_SHA1    
workflows:
  build_push_and_deploy_image:
    jobs:
      - builb
      - hold:
          type: approval
          requires:
            - builb
      - deploy:
          requires:
            - hold