version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  deploy: 
    docker:
      - image: dtzar/helm-kubectl
    steps:
      - checkout
      - run: 
          name: Install AWS cli
          command: | 
            apk add --no-cache curl jq py-pip
            pip install awscli
      - run:
          name: Get the kubeconfig file
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME
            cat ~/.kube/config
      - run:
          name: Helm Upgrade Or Install
          command: |
            helm upgrade helloapp ~/project/chart/hello/ --namespace default --set image.repository=686978187267.dkr.ecr.ap-southeast-1.amazonaws.com/helloapp --set image.tag=$CIRCLE_SHA1    
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build
          account-url: AWS_ECR_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: helloapp
          tag: "$CIRCLE_SHA1"
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold