version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  checkout:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: 
          name: checkout
          command: | 
            ls -la
            pwd
  build: 
    docker:
      - image: dtzar/helm-kubectl
    steps:
      - checkout
      - run: 
          name: Install AWS cli
          command: | 
            ls -la
            pwd  
      #- run:
      #    name: Install and confgure kubectl
      #    command: sudo curl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl && sudo chmod +x /usr/local/bin/kubectl
      #- run:
      #    name: Get the kubeconfig file
      #    command: |
      #      aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME
      #      cat ~/.kube/config      
#workflows:
#  build_and_push_image:
#    jobs:
      #- aws-ecr/build-and-push-image:
      #    account-url: AWS_ECR_URL
      #    aws-access-key-id: AWS_ACCESS_KEY_ID
      #    aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      #    create-repo: true
      #    dockerfile: Dockerfile
      #    path: .
      #    region: AWS_REGION
      #    repo: helloapp
      #    tag: "$CIRCLE_SHA1"
#      - build:
      #    requires:
      #      - aws-ecr/build-and-push-image